CREATE TABLE messages (
  uuid VARCHAR(36) DEFAULT (uuid()),
  content VARCHAR(255) NOT NULL,
  counter INT UNSIGNED DEFAULT NULL,
  created DATETIME NOT NULL DEFAULT NOW(),
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ( uuid )
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4;
